# Generated by Django 6.0 on 2025-12-15 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('reason', models.CharField(default='Blocked by system', max_length=255)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('manually_unblocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
