# Generated by Django 6.0 on 2025-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
